import type { ActorRef, Institute } from "./types";
import { districtEn, districtHi } from "./config/districts";

// All names, numbers and registries below are invented. No real person, officer or student appears.

const P = (s: string) => `${s}T00:00:00.000Z`;

function clerk(
  nameHi: string,
  nameEn: string,
  designationHi: string,
  designationEn: string,
  orgHi: string,
  orgEn: string,
  contactHint: string,
): ActorRef {
  return {
    role: "institute",
    nameHi,
    nameEn,
    designationHi,
    designationEn,
    orgHi,
    orgEn,
    contactHint,
  };
}

export const SEED_INSTITUTES: Institute[] = [
  {
    id: "inst-csjmu-arts",
    nameHi: "राजकीय महाविद्यालय, कल्याणपुर",
    nameEn: "Government Degree College, Kalyanpur",
    districtCode: "70",
    kind: "college",
    affiliatedTo: "छत्रपति शाहू जी महाराज विश्वविद्यालय, कानपुर",
    clerk: clerk(
      "श्री आर. के. वर्मा",
      "Shri R. K. Verma",
      "छात्रवृत्ति लिपिक",
      "Scholarship clerk",
      "राजकीय महाविद्यालय, कल्याणपुर",
      "Government Degree College, Kalyanpur",
      "छात्रवृत्ति प्रकोष्ठ, कक्ष 12",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-10"),
    courses: [
      {
        code: "BA",
        nameHi: "बी.ए.",
        nameEn: "B.A.",
        group: "general",
        years: 3,
        feeHeads: { tuition: 8500, exam: 1200, hostel: 0, mess: 0, caution: 500, library: 300, other: 0 },
        publishedAt: P("2026-08-10"),
      },
      {
        code: "BSC",
        nameHi: "बी.एस-सी.",
        nameEn: "B.Sc.",
        group: "general",
        years: 3,
        feeHeads: { tuition: 19800, exam: 1500, hostel: 12000, mess: 9000, caution: 1000, library: 400, other: 0 },
        publishedAt: P("2026-08-10"),
      },
      {
        // The master-data failure a student cannot fix: never published for this session.
        code: "BED",
        nameHi: "बी.एड.",
        nameEn: "B.Ed.",
        group: "tech",
        years: 2,
        feeHeads: { tuition: 51250, exam: 2000, hostel: 0, mess: 0, caution: 2000, library: 500, other: 0 },
        publishedAt: null,
      },
    ],
  },
  {
    id: "inst-akt-engg",
    nameHi: "श्री गंगा प्रसाद अभियंत्रण संस्थान, उन्नाव",
    nameEn: "Shri Ganga Prasad Institute of Engineering, Unnao",
    districtCode: "UN",
    kind: "college",
    affiliatedTo: "Dr. A.P.J. Abdul Kalam Technical University, Lucknow",
    clerk: clerk(
      "श्रीमती एस. निगम",
      "Smt. S. Nigam",
      "नोडल अधिकारी (छात्रवृत्ति)",
      "Nodal officer (scholarship)",
      "श्री गंगा प्रसाद अभियंत्रण संस्थान, उन्नाव",
      "Shri Ganga Prasad Institute of Engineering, Unnao",
      "प्रशासनिक भवन, प्रथम तल",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-12"),
    courses: [
      {
        code: "BTECHCS",
        nameHi: "बी.टेक (कंप्यूटर साइंस)",
        nameEn: "B.Tech (Computer Science)",
        group: "prof",
        years: 4,
        feeHeads: { tuition: 74500, exam: 3200, hostel: 46000, mess: 32000, caution: 5000, library: 1200, other: 0 },
        publishedAt: P("2026-08-12"),
      },
      {
        code: "DIPME",
        nameHi: "डिप्लोमा (मैकेनिकल)",
        nameEn: "Diploma (Mechanical)",
        group: "tech",
        years: 3,
        feeHeads: { tuition: 26400, exam: 1800, hostel: 21000, mess: 18000, caution: 2500, library: 600, other: 0 },
        publishedAt: P("2026-08-12"),
      },
    ],
  },
  {
    id: "inst-inter-lko",
    nameHi: "नगर पालिका इंटर कॉलेज, लखनऊ",
    nameEn: "Nagar Palika Inter College, Lucknow",
    districtCode: "72",
    kind: "school",
    affiliatedTo: null,
    clerk: clerk(
      "श्री डी. पी. मिश्रा",
      "Shri D. P. Mishra",
      "प्रधानाचार्य कार्यालय लिपिक",
      "Principal's office clerk",
      "नगर पालिका इंटर कॉलेज, लखनऊ",
      "Nagar Palika Inter College, Lucknow",
      "कार्यालय, मुख्य द्वार के पास",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-05"),
    courses: [
      {
        code: "CLASS11",
        nameHi: "कक्षा 11 (विज्ञान)",
        nameEn: "Class 11 (Science)",
        group: "school",
        years: 1,
        feeHeads: { tuition: 4200, exam: 600, hostel: 0, mess: 0, caution: 0, library: 200, other: 0 },
        publishedAt: P("2026-08-05"),
      },
      {
        code: "CLASS12",
        nameHi: "कक्षा 12 (विज्ञान)",
        nameEn: "Class 12 (Science)",
        group: "school",
        years: 1,
        feeHeads: { tuition: 4600, exam: 700, hostel: 0, mess: 0, caution: 0, library: 200, other: 0 },
        publishedAt: P("2026-08-05"),
      },
    ],
  },
  {
    id: "inst-school-gkp",
    nameHi: "राजकीय जूनियर हाई स्कूल, चौरी चौरा",
    nameEn: "Government Junior High School, Chauri Chaura",
    districtCode: "13",
    kind: "school",
    affiliatedTo: null,
    clerk: clerk(
      "श्री बी. के. यादव",
      "Shri B. K. Yadav",
      "प्रधानाध्यापक",
      "Head teacher",
      "राजकीय जूनियर हाई स्कूल, चौरी चौरा",
      "Government Junior High School, Chauri Chaura",
      "विद्यालय कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-04"),
    courses: [
      {
        code: "CLASS9",
        nameHi: "कक्षा 9",
        nameEn: "Class 9",
        group: "school",
        years: 1,
        feeHeads: { tuition: 0, exam: 300, hostel: 0, mess: 0, caution: 0, library: 0, other: 0 },
        publishedAt: P("2026-08-04"),
      },
      {
        code: "CLASS10",
        nameHi: "कक्षा 10",
        nameEn: "Class 10",
        group: "school",
        years: 1,
        feeHeads: { tuition: 0, exam: 350, hostel: 0, mess: 0, caution: 0, library: 0, other: 0 },
        publishedAt: P("2026-08-04"),
      },
    ],
  },
  {
    id: "inst-os-delhi",
    nameHi: "दिल्ली महाविद्यालय (उ0प्र0 के बाहर)",
    nameEn: "Delhi College (outside UP)",
    districtCode: "OS",
    kind: "college",
    affiliatedTo: null,
    clerk: clerk(
      "श्री पी. जोशी",
      "Shri P. Joshi",
      "छात्रवृत्ति समन्वयक",
      "Scholarship coordinator",
      "दिल्ली महाविद्यालय",
      "Delhi College",
      "छात्र कल्याण कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-18"),
    courses: [
      {
        code: "BCOM",
        nameHi: "बी.कॉम",
        nameEn: "B.Com",
        group: "general",
        years: 3,
        feeHeads: { tuition: 15600, exam: 1400, hostel: 38000, mess: 26000, caution: 3000, library: 800, other: 0 },
        publishedAt: P("2026-08-18"),
      },
    ],
  },
  {
    id: "inst-srmcem-lko",
    nameHi: "श्री रामस्वरूप मेमोरियल कॉलेज ऑफ इंजीनियरिंग एंड मैनेजमेंट, लखनऊ",
    nameEn: "SRMCEM, Lucknow — Shri Ramswaroop Memorial College of Engineering and Management",
    districtCode: "72",
    kind: "college",
    affiliatedTo: "Dr. A.P.J. Abdul Kalam Technical University, Lucknow",
    clerk: clerk(
      "श्रीमती के. तिवारी",
      "Smt. K. Tiwari",
      "छात्रवृत्ति लिपिक",
      "Scholarship clerk",
      "एस.आर.एम.सी.ई.एम., लखनऊ",
      "SRMCEM, Lucknow",
      "छात्र कल्याण, प्रशासनिक भवन",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-11"),
    courses: [
      {
        code: "BTECHCS",
        nameHi: "बी.टेक (कंप्यूटर साइंस)",
        nameEn: "B.Tech (Computer Science)",
        group: "prof",
        years: 4,
        // Tuition band from public 2025–26 aggregator listings (~₹1.03L/year). Hostel/exam struck out.
        feeHeads: { tuition: 103110, exam: 6000, hostel: 72000, mess: 42000, caution: 5000, library: 2000, other: 0 },
        publishedAt: P("2026-08-11"),
      },
      {
        code: "BBA",
        nameHi: "बी.बी.ए.",
        nameEn: "B.B.A.",
        group: "general",
        years: 3,
        feeHeads: { tuition: 62160, exam: 4000, hostel: 72000, mess: 42000, caution: 3000, library: 1500, other: 0 },
        publishedAt: P("2026-08-11"),
      },
    ],
  },
  {
    id: "inst-iet-lko",
    nameHi: "अभियांत्रिकी एवं प्रौद्योगिकी संस्थान, लखनऊ",
    nameEn: "Institute of Engineering and Technology, Lucknow",
    districtCode: "72",
    kind: "college",
    affiliatedTo: "Dr. A.P.J. Abdul Kalam Technical University, Lucknow",
    clerk: clerk(
      "श्री ए. खान",
      "Shri A. Khan",
      "नोडल अधिकारी",
      "Nodal officer",
      "आई.ई.टी. लखनऊ",
      "IET Lucknow",
      "छात्रवृत्ति कक्ष",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-09"),
    courses: [
      {
        code: "BTECHIT",
        nameHi: "बी.टेक (आई.टी.)",
        nameEn: "B.Tech (Information Technology)",
        group: "prof",
        years: 4,
        feeHeads: { tuition: 89850, exam: 5500, hostel: 38000, mess: 28000, caution: 4000, library: 1500, other: 0 },
        publishedAt: P("2026-08-09"),
      },
    ],
  },
  {
    id: "inst-hbtu-knp",
    nameHi: "हरकोर्ट बटलर तकनीकी विश्वविद्यालय, कानपुर",
    nameEn: "Harcourt Butler Technical University, Kanpur",
    districtCode: "70",
    kind: "university",
    affiliatedTo: "Harcourt Butler Technical University, Kanpur",
    clerk: clerk(
      "श्री एम. श्रीवास्तव",
      "Shri M. Srivastava",
      "छात्र कल्याण लिपिक",
      "Student welfare clerk",
      "एच.बी.टी.यू. कानपुर",
      "HBTU Kanpur",
      "छात्र कल्याण कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-08"),
    courses: [
      {
        code: "BTECHCHE",
        nameHi: "बी.टेक (केमिकल)",
        nameEn: "B.Tech (Chemical)",
        group: "prof",
        years: 4,
        feeHeads: { tuition: 125000, exam: 7000, hostel: 28000, mess: 24000, caution: 5000, library: 2000, other: 0 },
        publishedAt: P("2026-08-08"),
      },
    ],
  },
  {
    id: "inst-lu-arts",
    nameHi: "लखनऊ विश्वविद्यालय",
    nameEn: "University of Lucknow",
    districtCode: "72",
    kind: "university",
    affiliatedTo: "University of Lucknow",
    clerk: clerk(
      "श्रीमती आर. बंसल",
      "Smt. R. Bansal",
      "छात्रवृत्ति लिपिक",
      "Scholarship clerk",
      "लखनऊ विश्वविद्यालय",
      "University of Lucknow",
      "कला संकाय कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-07"),
    courses: [
      {
        code: "BA",
        nameHi: "बी.ए.",
        nameEn: "B.A.",
        group: "general",
        years: 3,
        feeHeads: { tuition: 7200, exam: 1100, hostel: 18000, mess: 14000, caution: 500, library: 200, other: 0 },
        publishedAt: P("2026-08-07"),
      },
    ],
  },
  {
    id: "inst-mgkvp-vns",
    nameHi: "महात्मा गांधी काशी विद्यापीठ, वाराणसी",
    nameEn: "Mahatma Gandhi Kashi Vidyapith, Varanasi",
    districtCode: "67",
    kind: "university",
    affiliatedTo: "Mahatma Gandhi Kashi Vidyapith, Varanasi",
    clerk: clerk(
      "श्री वी. पाण्डेय",
      "Shri V. Pandey",
      "छात्रवृत्ति लिपिक",
      "Scholarship clerk",
      "एम.जी.के.वी.पी. वाराणसी",
      "MGKVP Varanasi",
      "छात्र कल्याण",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-06"),
    courses: [
      {
        code: "BCOM",
        nameHi: "बी.कॉम",
        nameEn: "B.Com",
        group: "general",
        years: 3,
        feeHeads: { tuition: 9100, exam: 1300, hostel: 0, mess: 0, caution: 400, library: 250, other: 0 },
        publishedAt: P("2026-08-06"),
      },
    ],
  },
  {
    id: "inst-ds-aligarh",
    nameHi: "डी.एस. कॉलेज, अलीगढ़",
    nameEn: "D.S. College, Aligarh",
    districtCode: "28",
    kind: "college",
    affiliatedTo: "Dr. Bhimrao Ambedkar University, Agra",
    clerk: clerk(
      "श्री एन. शर्मा",
      "Shri N. Sharma",
      "छात्रवृत्ति लिपिक",
      "Scholarship clerk",
      "डी.एस. कॉलेज, अलीगढ़",
      "D.S. College, Aligarh",
      "कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-06"),
    courses: [
      {
        code: "BSC",
        nameHi: "बी.एस-सी.",
        nameEn: "B.Sc.",
        group: "general",
        years: 3,
        feeHeads: { tuition: 11200, exam: 1400, hostel: 0, mess: 0, caution: 600, library: 300, other: 0 },
        publishedAt: P("2026-08-06"),
      },
    ],
  },
  {
    id: "inst-gic-prayag",
    nameHi: "राजकीय इंटर कॉलेज, प्रयागराज",
    nameEn: "Government Inter College, Prayagraj",
    districtCode: "50",
    kind: "school",
    affiliatedTo: null,
    clerk: clerk(
      "श्री एस. त्रिपाठी",
      "Shri S. Tripathi",
      "प्रधानाचार्य कार्यालय लिपिक",
      "Principal's office clerk",
      "राजकीय इंटर कॉलेज, प्रयागराज",
      "Government Inter College, Prayagraj",
      "विद्यालय कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-05"),
    courses: [
      {
        code: "CLASS11",
        nameHi: "कक्षा 11 (कला)",
        nameEn: "Class 11 (Arts)",
        group: "school",
        years: 1,
        feeHeads: { tuition: 3800, exam: 500, hostel: 0, mess: 0, caution: 0, library: 150, other: 0 },
        publishedAt: P("2026-08-05"),
      },
      {
        code: "CLASS12",
        nameHi: "कक्षा 12 (कला)",
        nameEn: "Class 12 (Arts)",
        group: "school",
        years: 1,
        feeHeads: { tuition: 4000, exam: 550, hostel: 0, mess: 0, caution: 0, library: 150, other: 0 },
        publishedAt: P("2026-08-05"),
      },
    ],
  },
  {
    id: "inst-iti-vns",
    nameHi: "राजकीय औद्योगिक प्रशिक्षण संस्थान, वाराणसी",
    nameEn: "Government Industrial Training Institute, Varanasi",
    districtCode: "67",
    kind: "iti",
    affiliatedTo: "Uttar Pradesh Board of Technical Education",
    clerk: clerk(
      "श्री आर. मौर्य",
      "Shri R. Maurya",
      "प्रशिक्षण लिपिक",
      "Training clerk",
      "राजकीय आई.टी.आई. वाराणसी",
      "Government ITI Varanasi",
      "कार्यालय",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-04"),
    courses: [
      {
        code: "ITI-ELEC",
        nameHi: "आई.टी.आई. (इलेक्ट्रीशियन)",
        nameEn: "ITI (Electrician)",
        group: "tech",
        years: 2,
        feeHeads: { tuition: 6400, exam: 800, hostel: 0, mess: 0, caution: 500, library: 0, other: 0 },
        publishedAt: P("2026-08-04"),
      },
    ],
  },
  {
    id: "inst-other",
    nameHi: "अन्य — मेरा संस्थान सूची में नहीं है",
    nameEn: "Other — my institute is not listed",
    districtCode: "OT",
    kind: "college",
    affiliatedTo: null,
    clerk: clerk(
      "प्रतीक्षा — संस्थान जोड़ें",
      "Awaiting — add this institute",
      "मास्टर डेटा अप्रकाशित",
      "Master data unpublished",
      "अन्य संस्थान",
      "Unlisted institute",
      "संस्थान लिपिक से मास्टर डेटा प्रकाशित कराएँ",
    ),
    loginPin: "1234",
    masterDataPublishedAt: P("2026-08-01"),
    courses: [
      {
        code: "OTHER",
        nameHi: "अन्य / अनसूचीबद्ध पाठ्यक्रम",
        nameEn: "Other / unlisted course",
        group: "general",
        years: 3,
        feeHeads: { tuition: 10000, exam: 0, hostel: 0, mess: 0, caution: 0, library: 0, other: 0 },
        publishedAt: P("2026-08-01"),
      },
    ],
  },
];

const DWO_CODES = ["70", "72", "13", "UN", "67", "50", "28"] as const;

export const OPERATOR_LOGINS: {
  role: "institute" | "dwo";
  code: string;
  pin: string;
  labelHi: string;
  labelEn: string;
}[] = [
  ...SEED_INSTITUTES.filter((i) => i.id !== "inst-other").map((i) => ({
    role: "institute" as const,
    code: i.id,
    pin: "1234",
    labelHi: i.nameHi,
    labelEn: i.nameEn,
  })),
  ...DWO_CODES.map((code) => ({
    role: "dwo" as const,
    code,
    pin: "1234",
    labelHi: `जिला समाज कल्याण कार्यालय, ${districtHi(code)}`,
    labelEn: `District Welfare Office, ${districtEn(code)}`,
  })),
];

// Synthetic e-District certificate registry. Deliberately incomplete: a number that is not here
// verifies as not_found, which is the real failure students hit.
export const CERT_REGISTRY: Record<
  string,
  {
    kind: "income" | "caste";
    applicationNo: string;
    certNo: string;
    issuedOn: string;
    annualIncome?: number;
    holderDob: string;
  }
> = {
  "IC-2024-771201": {
    kind: "income",
    applicationNo: "APP-2024-771201",
    certNo: "IC-2024-771201",
    issuedOn: P("2024-07-12"),
    annualIncome: 96000,
    holderDob: "2007-04-11",
  },
  "IC-2021-330077": {
    kind: "income",
    applicationNo: "APP-2021-330077",
    certNo: "IC-2021-330077",
    issuedOn: P("2021-09-02"),
    annualIncome: 84000,
    holderDob: "2006-01-20",
  },
  "IC-2026-909090": {
    kind: "income",
    applicationNo: "APP-2026-909090",
    certNo: "IC-2026-909090",
    issuedOn: P("2026-02-14"),
    annualIncome: 268000,
    holderDob: "2005-11-03",
  },
  "CC-2019-118834": {
    kind: "caste",
    applicationNo: "APP-2019-118834",
    certNo: "CC-2019-118834",
    issuedOn: P("2019-05-30"),
    holderDob: "2007-04-11",
  },
  "CC-2023-556677": {
    kind: "caste",
    applicationNo: "APP-2023-556677",
    certNo: "CC-2023-556677",
    issuedOn: P("2023-01-19"),
    holderDob: "2006-01-20",
  },
};

export const BOARD_REGISTRY: Record<string, { board: "upmsp" | "cbse" | "icse"; rollNo: string; year: number }> = {
  "upmsp:2404771201": { board: "upmsp", rollNo: "2404771201", year: 2024 },
  "upmsp:2504330077": { board: "upmsp", rollNo: "2504330077", year: 2025 },
  "cbse:9911220044": { board: "cbse", rollNo: "9911220044", year: 2024 },
};

export const ENROLMENT_REGISTRY: Record<string, { instituteId: string; enrolmentNo: string }> = {
  "inst-csjmu-arts:CSJM2426BA0917": { instituteId: "inst-csjmu-arts", enrolmentNo: "CSJM2426BA0917" },
  "inst-csjmu-arts:CSJM2426BS1188": { instituteId: "inst-csjmu-arts", enrolmentNo: "CSJM2426BS1188" },
  "inst-akt-engg:AKTU2426CS4471": { instituteId: "inst-akt-engg", enrolmentNo: "AKTU2426CS4471" },
  "inst-os-delhi:DU2426BC7781": { instituteId: "inst-os-delhi", enrolmentNo: "DU2426BC7781" },
  "inst-srmcem-lko:SRMU2426CS1001": { instituteId: "inst-srmcem-lko", enrolmentNo: "SRMU2426CS1001" },
  "inst-iet-lko:IET2426IT2201": { instituteId: "inst-iet-lko", enrolmentNo: "IET2426IT2201" },
};

// Aadhaar-DBT (NPCI) seeding states, keyed by demo Aadhaar. Unknown numbers default to kyc_only,
// which is the most common real-world trap.
export const DBT_REGISTRY: Record<string, "seeded" | "kyc_only" | "dormant"> = {
  "000012340001": "seeded",
  "000012340002": "kyc_only",
  "000012340003": "dormant",
  "000012340004": "seeded",
  "000012340005": "seeded",
};

export const DEMO_HINTS = {
  aadhaarSeeded: "000012340001",
  aadhaarNotSeeded: "000012340002",
  incomeCertValid: "IC-2024-771201",
  incomeCertExpired: "IC-2021-330077",
  incomeCertOverCap: "IC-2026-909090",
  casteCert: "CC-2019-118834",
  boardRoll: "2404771201",
  enrolment: "CSJM2426BA0917",
};

export const SEED_PROFILES: any[] = [
  {
    id: "prof-priya-sharma",
    otr: "UP26-8000100001",
    mobile: "9876543210",
    aadhaarDemo: "000012340001",
    nameHi: "प्रिया शर्मा",
    nameEn: "Priya Sharma",
    fatherNameHi: "राकेश शर्मा",
    motherNameHi: "सुनीता शर्मा",
    dob: "2007-04-11",
    gender: "f",
    category: "general",
    districtCode: "70",
    addressHi: "12/45 कल्याणपुर, कानपुर नगर",
    photoRef: "demo",
    ekycAt: P("2026-08-01"),
    duplicateOtrs: [],
    createdAt: P("2026-08-01"),
  },
  {
    id: "prof-rahul-kumar",
    otr: "UP26-8000100002",
    mobile: "9876543211",
    aadhaarDemo: "000012340002",
    nameHi: "राहुल कुमार",
    nameEn: "Rahul Kumar",
    fatherNameHi: "रामेश्वर कुमार",
    motherNameHi: "कमलेश कुमारी",
    dob: "2006-01-20",
    gender: "m",
    category: "obc",
    districtCode: "70",
    addressHi: "45/A नौबस्ता, कानपुर नगर",
    photoRef: "demo",
    ekycAt: P("2026-08-02"),
    duplicateOtrs: [],
    createdAt: P("2026-08-02"),
  },
  {
    id: "prof-amit-verma",
    otr: "UP26-8000100003",
    mobile: "9876543212",
    aadhaarDemo: "000012340003",
    nameHi: "अमित वर्मा",
    nameEn: "Amit Verma",
    fatherNameHi: "सुरेश वर्मा",
    motherNameHi: "अनिता वर्मा",
    dob: "2005-11-03",
    gender: "m",
    category: "sc",
    districtCode: "70",
    addressHi: "88 स्वरूप नगर, कानपुर",
    photoRef: "demo",
    ekycAt: P("2026-08-03"),
    duplicateOtrs: [],
    createdAt: P("2026-08-03"),
  },
  {
    id: "prof-neha-gupta",
    otr: "UP26-8000100004",
    mobile: "9876543213",
    aadhaarDemo: "000012340004",
    nameHi: "नेहा गुप्ता",
    nameEn: "Neha Gupta",
    fatherNameHi: "विजय गुप्ता",
    motherNameHi: "सपना गुप्ता",
    dob: "2006-08-15",
    gender: "f",
    category: "general",
    districtCode: "72",
    addressHi: "101 हजरतगंज, लखनऊ",
    photoRef: "demo",
    ekycAt: P("2026-08-04"),
    duplicateOtrs: [],
    createdAt: P("2026-08-04"),
  },
  {
    id: "prof-vikram-singh",
    otr: "UP26-8000100005",
    mobile: "9876543214",
    aadhaarDemo: "000012340005",
    nameHi: "विक्रम सिंह",
    nameEn: "Vikram Singh",
    fatherNameHi: "हरिपाल सिंह",
    motherNameHi: "सुमन सिंह",
    dob: "2007-02-28",
    gender: "m",
    category: "st",
    districtCode: "13",
    addressHi: "55 चौरी चौरा, गोरखपुर",
    photoRef: "demo",
    ekycAt: P("2026-08-05"),
    duplicateOtrs: [],
    createdAt: P("2026-08-05"),
  },
];

export const SEED_CASES: any[] = [
  {
    id: "MLG-26-000101",
    session: "2026-27",
    profileId: "prof-priya-sharma",
    track: "dashmottar",
    cycle: "fresh",
    registrationNo: "270010120260001",
    instituteId: "inst-csjmu-arts",
    courseCode: "BA",
    stage: "institute_review",
    stageEnteredAt: P("2026-08-14"),
    owner: {
      role: "institute",
      nameHi: "श्री आर. के. वर्मा",
      designationHi: "छात्रवृत्ति लिपिक",
      orgHi: "राजकीय महाविद्यालय, कल्याणपुर",
    },
    dueAt: P("2026-09-12"),
    form: {
      rollNo: "2404771201",
      enrolmentNo: "CSJM2426BA0917",
      incomeCertNo: "IC-2024-771201",
      casteCertNo: "CC-2019-118834",
      hosteller: false,
    },
    preflight: [
      { id: "ekyc", state: "ok", titleHi: "आधार e-KYC", titleEn: "Aadhaar e-KYC", detailHi: "सत्यापित", detailEn: "Verified", actionHi: null, etaHi: null, fixedBy: "none" },
      { id: "dbt", state: "ok", titleHi: "NPCI DBT खाता लिंक", titleEn: "NPCI DBT Account Link", detailHi: "सक्रिय खाता मौजूद है", detailEn: "Active account present", actionHi: null, etaHi: null, fixedBy: "none" },
    ],
    certificates: {
      income: { applicationNo: "APP-2024-771201", certNo: "IC-2024-771201", issuedOn: P("2024-07-12"), annualIncome: 96000, state: "ok" },
      caste: { applicationNo: "APP-2019-118834", certNo: "CC-2019-118834", issuedOn: P("2019-05-30"), state: "ok" },
    },
    fee: {
      heads: { tuition: 8500, exam: 1200, hostel: 0, mess: 0, caution: 500, library: 300, other: 0 },
      nonRefundable: 8500,
    },
    estimate: {
      feeReimbursement: 8500,
      maintenancePerMonth: 700,
      months: 10,
      total: 15500,
      basisHi: "गैर-वापसी शुल्क ₹8,500 + रखरखाव भत्ता ₹7,000",
    },
    hardCopy: { dueAt: P("2026-08-20"), receivedAt: P("2026-08-16") },
    attendancePercent: 82,
    flags: [],
    correction: null,
    payment: {},
    escalations: [],
    grievanceDraftAt: null,
    events: [
      { at: P("2026-08-14"), type: "locked", actor: { role: "student", nameHi: "प्रिया शर्मा", designationHi: "छात्र", orgHi: "आवेदन" }, summaryHi: "आवेदन लॉक किया गया", summaryEn: "Application locked" },
    ],
    updatedAt: P("2026-08-16"),
  },
  {
    id: "MLG-26-000102",
    session: "2026-27",
    profileId: "prof-rahul-kumar",
    track: "dashmottar",
    cycle: "renewal",
    registrationNo: "270010120260002",
    instituteId: "inst-csjmu-arts",
    courseCode: "BSC",
    stage: "institute_review",
    stageEnteredAt: P("2026-08-10"),
    owner: {
      role: "institute",
      nameHi: "श्री आर. के. वर्मा",
      designationHi: "छात्रवृत्ति लिपिक",
      orgHi: "राजकीय महाविद्यालय, कल्याणपुर",
    },
    dueAt: P("2026-09-10"),
    form: {
      rollNo: "2504330077",
      enrolmentNo: "CSJM2426BS1188",
      incomeCertNo: "IC-2024-771201",
      hosteller: true,
    },
    preflight: [
      { id: "ekyc", state: "ok", titleHi: "आधार e-KYC", titleEn: "Aadhaar e-KYC", detailHi: "सत्यापित", detailEn: "Verified", actionHi: null, etaHi: null, fixedBy: "none" },
    ],
    certificates: {
      income: { applicationNo: "APP-2024-771201", certNo: "IC-2024-771201", issuedOn: P("2024-07-12"), annualIncome: 96000, state: "ok" },
    },
    fee: {
      heads: { tuition: 19800, exam: 1500, hostel: 12000, mess: 9000, caution: 1000, library: 400, other: 0 },
      nonRefundable: 19800,
    },
    estimate: {
      feeReimbursement: 19800,
      maintenancePerMonth: 1200,
      months: 10,
      total: 31800,
      basisHi: "गैर-वापसी शुल्क ₹19,800 + छात्रावास भत्ता ₹12,000",
    },
    hardCopy: { dueAt: P("2026-08-18"), receivedAt: null },
    attendancePercent: 91,
    flags: [],
    correction: null,
    payment: {},
    escalations: [],
    grievanceDraftAt: null,
    events: [],
    updatedAt: P("2026-08-10"),
  },
  {
    id: "MLG-26-000103",
    session: "2026-27",
    profileId: "prof-amit-verma",
    track: "dashmottar",
    cycle: "fresh",
    registrationNo: "270010120260003",
    instituteId: "inst-csjmu-arts",
    courseCode: "BA",
    stage: "dwo_review",
    stageEnteredAt: P("2026-08-18"),
    owner: {
      role: "dwo",
      nameHi: "जिला समाज कल्याण अधिकारी",
      designationHi: "जिला समाज कल्याण अधिकारी",
      orgHi: "जिला कार्यालय, कानपुर नगर",
    },
    dueAt: P("2026-09-25"),
    form: {
      rollNo: "2404771201",
      enrolmentNo: "CSJM2426BA0917",
      incomeCertNo: "IC-2024-771201",
      casteCertNo: "CC-2019-118834",
      hosteller: false,
    },
    preflight: [],
    certificates: {
      income: { applicationNo: "APP-2024-771201", certNo: "IC-2024-771201", issuedOn: P("2024-07-12"), annualIncome: 96000, state: "ok" },
      caste: { applicationNo: "APP-2019-118834", certNo: "CC-2019-118834", issuedOn: P("2019-05-30"), state: "ok" },
    },
    fee: {
      heads: { tuition: 8500, exam: 1200, hostel: 0, mess: 0, caution: 500, library: 300, other: 0 },
      nonRefundable: 8500,
    },
    estimate: {
      feeReimbursement: 8500,
      maintenancePerMonth: 700,
      months: 10,
      total: 15500,
      basisHi: "गैर-वापसी शुल्क ₹8,500 + रखरखाव भत्ता ₹7,000",
    },
    hardCopy: { dueAt: P("2026-08-20"), receivedAt: P("2026-08-16") },
    attendancePercent: 85,
    flags: [],
    correction: null,
    payment: {},
    escalations: [],
    grievanceDraftAt: null,
    events: [],
    updatedAt: P("2026-08-18"),
  },
  {
    id: "MLG-26-000104",
    session: "2026-27",
    profileId: "prof-neha-gupta",
    track: "dashmottar",
    cycle: "fresh",
    registrationNo: "270010220260004",
    instituteId: "inst-akt-engg",
    courseCode: "BTECHCS",
    stage: "dwo_review",
    stageEnteredAt: P("2026-08-19"),
    owner: {
      role: "dwo",
      nameHi: "जिला समाज कल्याण अधिकारी",
      designationHi: "जिला समाज कल्याण अधिकारी",
      orgHi: "जिला कार्यालय, कानपुर नगर",
    },
    dueAt: P("2026-09-26"),
    form: {
      rollNo: "cbse:9911220044",
      enrolmentNo: "AKTU2426CS4471",
      incomeCertNo: "IC-2024-771201",
      hosteller: true,
    },
    preflight: [],
    certificates: {
      income: { applicationNo: "APP-2024-771201", certNo: "IC-2024-771201", issuedOn: P("2024-07-12"), annualIncome: 96000, state: "ok" },
    },
    fee: {
      heads: { tuition: 74500, exam: 3200, hostel: 46000, mess: 32000, caution: 5000, library: 1200, other: 0 },
      nonRefundable: 74500,
    },
    estimate: {
      feeReimbursement: 74500,
      maintenancePerMonth: 1200,
      months: 10,
      total: 86500,
      basisHi: "गैर-वापसी शुल्क ₹74,500 + छात्रावास भत्ता ₹12,000",
    },
    hardCopy: { dueAt: P("2026-08-22"), receivedAt: P("2026-08-18") },
    attendancePercent: 94,
    flags: [],
    correction: null,
    payment: {},
    escalations: [],
    grievanceDraftAt: null,
    events: [],
    updatedAt: P("2026-08-19"),
  },
  {
    id: "MLG-26-000105",
    session: "2026-27",
    profileId: "prof-vikram-singh",
    track: "post_inter",
    cycle: "renewal",
    registrationNo: "272010120260005",
    instituteId: "inst-inter-lko",
    courseCode: "CLASS12",
    stage: "dwo_review",
    stageEnteredAt: P("2026-08-15"),
    owner: {
      role: "dwo",
      nameHi: "जिला समाज कल्याण अधिकारी",
      designationHi: "जिला समाज कल्याण अधिकारी",
      orgHi: "जिला कार्यालय, लखनऊ",
    },
    dueAt: P("2026-09-20"),
    form: {
      rollNo: "upmsp:2404771201",
      incomeCertNo: "IC-2024-771201",
      casteCertNo: "CC-2019-118834",
      hosteller: false,
    },
    preflight: [],
    certificates: {
      income: { applicationNo: "APP-2024-771201", certNo: "IC-2024-771201", issuedOn: P("2024-07-12"), annualIncome: 96000, state: "ok" },
      caste: { applicationNo: "APP-2019-118834", certNo: "CC-2019-118834", issuedOn: P("2019-05-30"), state: "ok" },
    },
    fee: {
      heads: { tuition: 4600, exam: 700, hostel: 0, mess: 0, caution: 0, library: 200, other: 0 },
      nonRefundable: 4600,
    },
    estimate: {
      feeReimbursement: 4600,
      maintenancePerMonth: 380,
      months: 10,
      total: 8400,
      basisHi: "गैर-वापसी शुल्क ₹4,600 + रखरखाव भत्ता ₹3,800",
    },
    hardCopy: { dueAt: P("2026-08-18"), receivedAt: P("2026-08-16") },
    attendancePercent: 88,
    flags: [],
    correction: null,
    payment: {},
    escalations: [],
    grievanceDraftAt: null,
    events: [],
    updatedAt: P("2026-08-15"),
  },
];
